//! Built-in search keywords for common emoji, plus optional user TOML.

use std::collections::HashMap;
use std::fs;
use std::path::Path;

/// Extra descriptors keyed by emoji character.
/// These are merged into the search blob so everyday queries hit the right glyph.
pub fn builtin_aliases() -> HashMap<String, String> {
    let pairs: &[(&str, &str)] = &[
        // Food / drink / Tims-ish
        ("🍩", "donut doughnut timbit timbits snack dessert pastry hole"),
        ("🍪", "cookie biscuit dessert snack"),
        ("🧁", "cupcake muffin dessert cake"),
        ("🍰", "cake birthday dessert"),
        ("☕", "coffee cafe tea hot drink latte espresso"),
        ("🍵", "tea green matcha hot drink"),
        ("🍺", "beer drink alcohol pub"),
        ("🍻", "beer cheers drink alcohol"),
        ("🍷", "wine drink alcohol"),
        ("🍕", "pizza food italian"),
        ("🍔", "burger hamburger food"),
        ("🍟", "fries chips food"),
        ("🌮", "taco food mexican"),
        ("🍣", "sushi food japanese fish"),
        ("🍜", "ramen noodles soup food"),
        ("🍎", "apple fruit red"),
        ("🍌", "banana fruit"),
        // Faces / slang
        ("😀", "happy smile grin cheerful"),
        ("😃", "happy smile grin"),
        ("😄", "happy smile laugh"),
        ("😁", "grin smile happy"),
        ("😆", "laugh haha funny"),
        ("😅", "sweat nervous awkward smile"),
        ("🤣", "rofl lmao laughing funny rolling"),
        ("😂", "lol lmao laughing cry funny haha tears"),
        ("🙂", "smile slight happy"),
        ("😊", "blush smile happy shy"),
        ("😇", "angel innocent halo"),
        ("🥰", "love hearts smile adore"),
        ("😍", "love heart eyes crush"),
        ("🤩", "star eyes wow excited"),
        ("😘", "kiss blow love"),
        ("😗", "kiss"),
        ("😚", "kiss closed eyes"),
        ("😙", "kiss smile"),
        ("🥲", "tear smile bittersweet"),
        ("😋", "yum tasty delicious tongue"),
        ("😛", "tongue out silly"),
        ("😜", "wink tongue silly"),
        ("🤪", "zany crazy wild"),
        ("😝", "tongue closed eyes silly"),
        ("🤑", "money rich dollar"),
        ("🤗", "hug hugz"),
        ("🤭", "oops secret giggle"),
        ("🤫", "shh quiet secret silence"),
        ("🤔", "think thinking hmm ponder"),
        ("🤐", "zip silence secret"),
        ("🤨", "raised eyebrow skeptic hmm"),
        ("😐", "neutral meh blank"),
        ("😑", "expressionless meh"),
        ("😶", "speechless silent"),
        ("😏", "smirk sly"),
        ("😒", "unamused meh annoyed"),
        ("🙄", "eyeroll eye roll whatever"),
        ("😬", "grimace awkward"),
        ("😮‍💨", "exhale sigh relief"),
        ("🤥", "lie pinocchio"),
        ("😌", "relieved calm"),
        ("😔", "sad pensive down"),
        ("😪", "sleepy tired"),
        ("🤤", "drool hungry"),
        ("😴", "sleep zzz tired"),
        ("😷", "mask sick covid"),
        ("🤒", "sick fever ill"),
        ("🤕", "hurt injured bandage"),
        ("🤢", "nauseated sick green"),
        ("🤮", "vomit puke sick"),
        ("🥵", "hot heat sweating"),
        ("🥶", "cold freeze freezing"),
        ("🥴", "woozy drunk dizzy"),
        ("😵", "dizzy dead ko"),
        ("🤯", "mind blown explode"),
        ("🤠", "cowboy hat western"),
        ("🥳", "party celebrate birthday"),
        ("😎", "cool sunglasses swag"),
        ("🤓", "nerd geek glasses"),
        ("🧐", "monocle inspect fancy"),
        ("😕", "confused puzzled"),
        ("😟", "worried sad"),
        ("🙁", "frown sad"),
        ("☹️", "frown sad"),
        ("😮", "wow open mouth surprised"),
        ("😯", "hushed surprise"),
        ("😲", "astonished shock"),
        ("😳", "flushed embarrassed blush"),
        ("🥺", "pleading puppy eyes please cute"),
        ("😦", "frown open mouth"),
        ("😧", "anguished"),
        ("😨", "fear scared"),
        ("😰", "anxious sweat worry"),
        ("😥", "sad relieved sweat"),
        ("😢", "cry sad tear"),
        ("😭", "sob cry bawling sad"),
        ("😱", "scream fear shock munch"),
        ("😖", "confounded frustrated"),
        ("😣", "persevering strained"),
        ("😞", "disappointed sad"),
        ("😓", "downcast sweat"),
        ("😩", "weary tired exhausted"),
        ("😫", "tired exhausted"),
        ("🥱", "yawn bored tired"),
        ("😤", "triumph hmph steam"),
        ("😡", "angry mad rage red"),
        ("😠", "angry mad"),
        ("🤬", "cursing swear symbols mad"),
        ("😈", "devil smile evil"),
        ("👿", "imp angry devil"),
        ("💀", "skull dead death"),
        ("☠️", "skull crossbones dead pirate"),
        ("💩", "poop poo shit crap"),
        ("🤡", "clown funny"),
        ("👹", "ogre monster japanese"),
        ("👺", "goblin japanese"),
        ("👻", "ghost halloween boo"),
        ("👽", "alien ufo space"),
        ("👾", "alien monster game space invader"),
        ("🤖", "robot bot ai"),
        ("😺", "cat smile"),
        ("😸", "cat grin"),
        ("😹", "cat joy tears laugh"),
        ("😻", "cat heart eyes love"),
        ("😼", "cat smirk"),
        ("😽", "cat kiss"),
        ("🙀", "cat scream shock"),
        ("😿", "cat cry sad"),
        ("😾", "cat pouting angry"),
        // Gestures
        ("👍", "thumbsup yes ok good approve +1 like"),
        ("👎", "thumbsdown no bad dislike -1"),
        ("👌", "ok okay perfect"),
        ("✌️", "peace victory two"),
        ("🤞", "fingers crossed luck hope"),
        ("🤟", "love you gesture"),
        ("🤘", "rock metal horns"),
        ("🤙", "call me shaka hang loose"),
        ("👈", "point left"),
        ("👉", "point right"),
        ("👆", "point up"),
        ("👇", "point down"),
        ("☝️", "index up point"),
        ("✋", "hand stop high five"),
        ("🤚", "raised back hand"),
        ("🖐️", "hand splayed"),
        ("🖖", "vulcan spock star trek"),
        ("👋", "wave hello hi bye"),
        ("🤝", "handshake deal agree"),
        ("🙏", "pray please thanks namaste"),
        ("💪", "muscle strong flex gym"),
        ("🦾", "mechanical arm robot strong"),
        ("✍️", "writing pen hand"),
        ("👏", "clap applause bravo"),
        ("🙌", "raised hands celebrate hooray"),
        ("👐", "open hands"),
        ("🤲", "palms up together"),
        ("🫂", "hug people"),
        // Hearts / love
        ("❤️", "heart love red romance"),
        ("🧡", "heart orange love"),
        ("💛", "heart yellow love"),
        ("💚", "heart green love"),
        ("💙", "heart blue love"),
        ("💜", "heart purple love"),
        ("🖤", "heart black love"),
        ("🤍", "heart white love"),
        ("🤎", "heart brown love"),
        ("💔", "broken heart sad breakup"),
        ("❣️", "heart exclamation love"),
        ("💕", "two hearts love"),
        ("💞", "revolving hearts love"),
        ("💓", "beating heart love"),
        ("💗", "growing heart love"),
        ("💖", "sparkling heart love"),
        ("💘", "cupid heart arrow love"),
        ("💝", "heart ribbon gift love"),
        // Nature / Canada
        ("🍁", "maple leaf canada autumn fall leaf"),
        ("🍂", "fallen leaf autumn"),
        ("🍃", "leaf wind flutter"),
        ("🌲", "evergreen tree pine forest"),
        ("🌳", "tree deciduous forest"),
        ("🌴", "palm tree tropical"),
        ("🌵", "cactus desert"),
        ("🌸", "cherry blossom sakura flower"),
        ("🌺", "hibiscus flower"),
        ("🌻", "sunflower flower"),
        ("🌹", "rose flower love"),
        ("🌷", "tulip flower"),
        ("🌱", "seedling plant grow"),
        ("🌍", "earth africa europe globe world"),
        ("🌎", "earth americas globe world"),
        ("🌏", "earth asia globe world"),
        ("🌕", "full moon"),
        ("🌙", "crescent moon night"),
        ("⭐", "star"),
        ("🌟", "glowing star sparkle"),
        ("✨", "sparkles magic shiny"),
        ("⚡", "lightning zap electricity power"),
        ("🔥", "fire lit flame hot lit af"),
        ("💧", "droplet water sweat"),
        ("🌊", "wave ocean water"),
        ("❄️", "snow snowflake cold winter"),
        ("☃️", "snowman winter"),
        ("☔", "umbrella rain weather"),
        ("🌈", "rainbow pride weather"),
        ("☀️", "sun sunny weather"),
        ("🌤️", "sun cloud weather"),
        // Work / tech
        ("💻", "laptop computer work code"),
        ("🖥️", "desktop computer work"),
        ("⌨️", "keyboard type code"),
        ("🖱️", "mouse computer"),
        ("📱", "phone mobile iphone"),
        ("📧", "email mail"),
        ("📨", "incoming envelope mail"),
        ("📩", "envelope arrow mail"),
        ("📬", "mailbox mail"),
        ("📁", "folder file"),
        ("📂", "folder open file"),
        ("📄", "page document file"),
        ("📝", "memo note write"),
        ("📊", "chart bar graph stats"),
        ("📈", "chart up growth gain"),
        ("📉", "chart down loss"),
        ("🔔", "bell notification alert"),
        ("🔕", "bell slash mute silent"),
        ("🔒", "lock locked secure"),
        ("🔓", "unlock open"),
        ("🔑", "key password"),
        ("🛠️", "tools fix repair"),
        ("⚙️", "gear settings config"),
        ("🔧", "wrench tool fix"),
        ("🔨", "hammer tool"),
        ("💣", "bomb explode"),
        ("🚀", "rocket ship launch deploy space"),
        ("✈️", "airplane plane travel flight"),
        ("🚗", "car auto vehicle"),
        ("🚕", "taxi cab"),
        ("🚌", "bus transit"),
        ("🚇", "metro subway train"),
        ("🏠", "home house"),
        ("🏢", "office building work"),
        ("🏥", "hospital medical"),
        ("🏦", "bank money"),
        ("🏫", "school education"),
        // Symbols
        ("✅", "check checkmark yes done ok done"),
        ("❌", "x cross no wrong cancel"),
        ("❎", "cross mark button no"),
        ("✔️", "check heavy yes"),
        ("☑️", "ballot box check"),
        ("❗", "exclamation alert bang"),
        ("❓", "question mark help"),
        ("💯", "hundred 100 perfect score"),
        ("🆕", "new"),
        ("🆙", "up"),
        ("🆗", "ok okay"),
        ("🆘", "sos help emergency"),
        ("🔞", "18 underage adult"),
        ("⚠️", "warning caution alert"),
        ("🚫", "prohibited no ban forbidden"),
        ("♻️", "recycle green"),
        ("⚜️", "fleur de lis quebec"),
        // Country flags: primary terms also come from emoji_db::flag_search_terms
        // ("flag: Canada" → canada, canadian flag, …). Keep rich extras here.
        (
            "🇨🇦",
            "canada canadian canadian flag canada flag maple leaf north america",
        ),
        (
            "🇺🇸",
            "usa us america american americans american flag usa flag stars and stripes united states of america",
        ),
        (
            "🇬🇧",
            "uk britain british british flag uk flag great britain union jack england",
        ),
        (
            "🇫🇷",
            "france french french flag france flag paris",
        ),
        (
            "🇩🇪",
            "germany german german flag deutschland",
        ),
        (
            "🇯🇵",
            "japan japanese japanese flag nippon",
        ),
        (
            "🇲🇽",
            "mexico mexican mexican flag",
        ),
        (
            "🇧🇷",
            "brazil brazilian brazilian flag",
        ),
        (
            "🇮🇳",
            "india indian indian flag",
        ),
        (
            "🇦🇺",
            "australia australian aussie australian flag",
        ),
        // Animals (common searches)
        ("🐶", "dog puppy pet"),
        ("🐱", "cat kitten pet"),
        ("🐭", "mouse"),
        ("🐹", "hamster pet"),
        ("🐰", "rabbit bunny"),
        ("🦊", "fox"),
        ("🐻", "bear"),
        ("🐼", "panda"),
        ("🐨", "koala"),
        ("🐯", "tiger"),
        ("🦁", "lion"),
        ("🐮", "cow"),
        ("🐷", "pig"),
        ("🐸", "frog"),
        ("🐵", "monkey"),
        ("🐔", "chicken"),
        ("🐧", "penguin"),
        ("🐦", "bird"),
        ("🐤", "chick baby bird"),
        ("🦆", "duck"),
        ("🦅", "eagle"),
        ("🦉", "owl"),
        ("🦇", "bat"),
        ("🐺", "wolf"),
        ("🐗", "boar"),
        ("🐴", "horse"),
        ("🦄", "unicorn magic"),
        ("🐝", "bee honey"),
        ("🐛", "bug insect"),
        ("🦋", "butterfly"),
        ("🐌", "snail"),
        ("🐞", "ladybug beetle"),
        ("🐜", "ant"),
        ("🦟", "mosquito"),
        ("🦗", "cricket"),
        ("🕷️", "spider"),
        ("🦂", "scorpion"),
        ("🐢", "turtle"),
        ("🐍", "snake"),
        ("🦎", "lizard"),
        ("🦖", "trex dinosaur"),
        ("🦕", "sauropod dinosaur"),
        ("🐙", "octopus"),
        ("🦑", "squid"),
        ("🦐", "shrimp"),
        ("🦞", "lobster"),
        ("🦀", "crab"),
        ("🐡", "blowfish fish"),
        ("🐠", "tropical fish"),
        ("🐟", "fish"),
        ("🐬", "dolphin"),
        ("🐳", "whale"),
        ("🐋", "whale"),
        ("🦈", "shark"),
        ("🐊", "crocodile"),
        ("🐅", "tiger"),
        ("🐆", "leopard"),
        ("🦓", "zebra"),
        ("🦍", "gorilla"),
        ("🦧", "orangutan"),
        ("🐘", "elephant"),
        ("🦛", "hippo"),
        ("🦏", "rhino"),
        ("🐪", "camel"),
        ("🐫", "camel two hump"),
        ("🦒", "giraffe"),
        ("🦘", "kangaroo"),
        ("🦬", "bison"),
        ("🐃", "water buffalo"),
        ("🐂", "ox"),
        ("🐄", "cow"),
        ("🐎", "horse race"),
        ("🐖", "pig"),
        ("🐏", "ram"),
        ("🐑", "sheep ewe"),
        ("🦙", "llama alpaca"),
        ("🐐", "goat"),
        ("🦌", "deer"),
        ("🐕", "dog"),
        ("🐩", "poodle dog"),
        ("🦮", "guide dog"),
        ("🐈", "cat"),
        ("🪶", "feather"),
        ("🦃", "turkey"),
        ("🦤", "dodo"),
        ("🦚", "peacock"),
        ("🦜", "parrot"),
        ("🦢", "swan"),
        ("🦩", "flamingo"),
        ("🕊️", "dove peace"),
        ("🐇", "rabbit"),
        ("🦝", "raccoon"),
        ("🦨", "skunk"),
        ("🦡", "badger"),
        ("🦫", "beaver canada"),
        ("🦦", "otter"),
        ("🦥", "sloth"),
        ("🐁", "mouse"),
        ("🐀", "rat"),
        ("🐿️", "chipmunk squirrel"),
        ("🦔", "hedgehog"),
        // Activities / sports
        ("⚽", "soccer football sport"),
        ("🏀", "basketball sport"),
        ("🏈", "football american sport"),
        ("⚾", "baseball sport"),
        ("🎾", "tennis sport"),
        ("🏐", "volleyball sport"),
        ("🏉", "rugby sport"),
        ("🎱", "pool 8ball billiards"),
        ("🏓", "ping pong table tennis"),
        ("🏸", "badminton"),
        ("🏒", "hockey ice canada sport"),
        ("🏑", "field hockey"),
        ("🥅", "goal net sport"),
        ("⛳", "golf flag"),
        ("🏹", "bow arrow archery"),
        ("🎣", "fishing"),
        ("🤿", "diving mask snorkel"),
        ("🥊", "boxing glove fight"),
        ("🥋", "martial arts judo karate"),
        ("🎽", "running shirt sport"),
        ("🛹", "skateboard"),
        ("🛼", "roller skate"),
        ("🛷", "sled"),
        ("⛸️", "ice skate"),
        ("🥌", "curling stone canada"),
        ("🎿", "ski snow"),
        ("⛷️", "skier snow"),
        ("🏂", "snowboard"),
        ("🪂", "parachute"),
        ("🏋️", "weightlifter gym lift"),
        ("🤼", "wrestlers"),
        ("🤸", "cartwheel gymnastics"),
        ("⛹️", "basketball person sport"),
        ("🤺", "fencing"),
        ("🤾", "handball"),
        ("🏌️", "golf person"),
        ("🏇", "horse racing"),
        ("🧘", "yoga meditation"),
        ("🏄", "surf surfing"),
        ("🏊", "swim swimming"),
        ("🤽", "water polo"),
        ("🚣", "rowboat"),
        ("🧗", "climb climbing"),
        ("🚵", "mountain bike"),
        ("🚴", "bike bicycle cycling"),
        ("🏆", "trophy win champion award"),
        ("🥇", "gold medal first win"),
        ("🥈", "silver medal second"),
        ("🥉", "bronze medal third"),
        ("🏅", "medal sports"),
        ("🎖️", "military medal"),
        ("🏵️", "rosette"),
        ("🎗️", "reminder ribbon"),
        ("🎫", "ticket"),
        ("🎟️", "admission tickets"),
        ("🎪", "circus tent"),
        ("🤹", "juggle"),
        ("🎭", "performing arts theater theatre drama"),
        ("🩰", "ballet shoes dance"),
        ("🎨", "art palette paint creative"),
        ("🎬", "clapper film movie"),
        ("🎤", "microphone sing karaoke"),
        ("🎧", "headphones music audio"),
        ("🎼", "musical score music"),
        ("🎹", "piano keyboard music"),
        ("🥁", "drum music"),
        ("🪘", "long drum"),
        ("🎷", "saxophone jazz music"),
        ("🎺", "trumpet music"),
        ("🎸", "guitar music rock"),
        ("🪕", "banjo music"),
        ("🎻", "violin music"),
        ("🎲", "dice game random"),
        ("♟️", "chess pawn game"),
        ("🎯", "dart target bullseye"),
        ("🎳", "bowling"),
        ("🎮", "video game controller gaming"),
        ("🕹️", "joystick game"),
        ("🎰", "slot machine gambling"),
        ("🧩", "puzzle piece jigsaw"),
    ];

    let mut map = HashMap::with_capacity(pairs.len());
    for (ch, kws) in pairs {
        map.insert((*ch).to_string(), (*kws).to_string());
    }
    map
}

/// Load optional `~/.config/timbits/emoji_aliases.toml`:
///
/// ```toml
/// [aliases]
/// "🍩" = "timbit snack"
/// ```
pub fn load_user_aliases(path: &Path) -> HashMap<String, String> {
    let Ok(raw) = fs::read_to_string(path) else {
        return HashMap::new();
    };
    #[derive(serde::Deserialize, Default)]
    struct File {
        #[serde(default)]
        aliases: HashMap<String, String>,
    }
    match toml::from_str::<File>(&raw) {
        Ok(f) => f.aliases,
        Err(e) => {
            log::warn!("emoji aliases parse {}: {e}", path.display());
            HashMap::new()
        }
    }
}

/// Merge built-in + user aliases (user wins on duplicate keys by appending).
pub fn merged_aliases(user_path: &Path) -> HashMap<String, String> {
    let mut map = builtin_aliases();
    for (k, v) in load_user_aliases(user_path) {
        map.entry(k)
            .and_modify(|existing| {
                existing.push(' ');
                existing.push_str(&v);
            })
            .or_insert(v);
    }
    map
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn has_donut_alias() {
        let m = builtin_aliases();
        let k = m.get("🍩").expect("donut");
        assert!(k.contains("donut"));
        assert!(k.contains("timbit"));
    }
}
